import { mkdir, writeFile, cp, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { compareRound, round } from '../js/demo-data.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const origin = 'https://data2gain.com';
const app = 'https://app.data2gain.com/';
const slugs = { es: { home: '', players: 'jugadores/', coaches: 'coaches/', info: 'informacion/' }, en: { home: '', players: 'players/', coaches: 'coaches/', info: 'information/' } };
let lang = 'es';
const t = (es, en) => lang === 'es' ? es : en;
const route = (page, locale = lang) => `/${locale}/${slugs[locale][page]}`;
const esc = text => String(text).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const arrow = '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none"><path d="M5 12h14M13 6l6 6-6 6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const diagonal = '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none"><path d="M6 18 18 6M6 6h12v12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const check = '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none"><path d="m5 12 4 4 10-10" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const link = (href, text, kind = 'gold', tracking = '') => `<a class="button button-${kind}" href="${esc(href)}"${tracking ? ` data-track="${tracking}"` : ''}>${text}${arrow}</a>`;
const mail = subject => `mailto:info@data2gain.com?subject=${encodeURIComponent(subject)}`;
const eyebrow = text => `<p class="eyebrow">${text}</p>`;
const brand = () => `<span class="brand"><img src="/assets/logo-64.webp" width="32" height="32" alt=""><span>DATA<span class="brand-two">2</span>GAIN</span></span>`;

function header(page) {
  return `<a class="skip-link" href="#main">${t('Saltar al contenido', 'Skip to content')}</a>
  <header class="site-header"><div class="container header-inner">
    <a class="brand-link" href="${route('home')}" aria-label="${t('Data2Gain, inicio','Data2Gain, home')}">${brand()}</a>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav" aria-label="${t('Abrir menú','Open menu')}"><span></span><span></span></button>
    <nav id="main-nav" class="main-nav" aria-label="${t('Navegación principal','Main navigation')}">
      <a href="${route('players')}"${page === 'players' ? ' aria-current="page"' : ''}>${t('Jugadores','Players')}</a>
      <a href="${route('coaches')}"${page === 'coaches' ? ' aria-current="page"' : ''}>Coaches</a>
      <a href="${route('home')}#como-funciona">${t('Cómo funciona','How it works')}</a>
      <a href="${route('home')}#precios">${t('Precios','Pricing')}</a>
      <div class="nav-utilities"><div class="languages" aria-label="${t('Idioma','Language')}"><a href="${route(page,'es')}" lang="es" hreflang="es" aria-label="Español"${lang === 'es' ? ' aria-current="true"' : ''}>ES</a><span aria-hidden="true">/</span><a href="${route(page,'en')}" lang="en" hreflang="en" aria-label="English"${lang === 'en' ? ' aria-current="true"' : ''}>EN</a></div>
      <a class="nav-access" href="${app}" data-track="app_open">${t('Acceder','Sign in')}${diagonal}</a></div>
    </nav>
  </div></header>`;
}

function footer() {
  return `<footer class="site-footer"><div class="container"><div class="footer-top"><div><a class="brand-link" href="${route('home')}" aria-label="${t('Data2Gain, inicio','Data2Gain, home')}">${brand()}</a><p>${t('Tu juego. Tus datos. Tu siguiente paso.','Your game. Your data. Your next step.')}</p></div><nav aria-label="${t('Enlaces del pie','Footer navigation')}"><a href="${route('players')}">${t('Jugadores','Players')}</a><a href="${route('coaches')}">Coaches</a><a href="${route('home')}#precios">${t('Precios','Pricing')}</a><a href="mailto:info@data2gain.com">${t('Contacto','Contact')}</a></nav></div><div class="footer-bottom"><span>© 2026 Data2Gain</span><a href="${route('info')}">${t('Información y contacto','Information & contact')}</a><span class="footer-location">${t('Golf, con perspectiva.','A new perspective on golf.')}</span></div></div></footer>
  <dialog class="image-dialog" aria-labelledby="image-dialog-title"><div class="dialog-top"><p id="image-dialog-title">${t('Detalle del producto','Product detail')}</p><button type="button" class="dialog-close" aria-label="${t('Cerrar imagen','Close image')}">×</button></div><img alt=""></dialog>`;
}

function hero(page) {
  const home = page === 'home';
  const coach = page === 'coaches';
  const title = home ? t('Convierte cada ronda<br>en una <em>ventaja.</em>', 'Turn every round<br>into an <em>advantage.</em>') : coach ? t('Tu criterio.<br>Sus datos.<br><em>Más perspectiva.</em>','Your expertise.<br>Their data.<br><em>More perspective.</em>') : t('Conoce tu juego.<br>Encuentra tu<br><em>siguiente paso.</em>','Know your game.<br>Find your<br><em>next step.</em>');
  const desc = home ? t('Entiende dónde ganas golpes, dónde los pierdes y qué trabajar después. Analítica de golf para jugadores y coaches.', 'See where you gain strokes, where you lose them and what to work on next. Golf analytics for players and coaches.') : coach ? t('Pon el análisis de las rondas al servicio de tu experiencia. Una visión más completa para orientar cada sesión con tus alumnos.', 'Bring round analysis into your coaching. A clearer picture of each player to inform every practice session.') : t('Tus rondas cuentan una historia. Descubre tus patrones con Strokes Gained, distancias reales y una IA que pone tus datos en contexto.', 'Your rounds tell a story. Discover your patterns with Strokes Gained, real club distances and AI that puts your data in context.');
  return `<section class="hero ${home ? 'hero-home' : 'hero-detail'}"><div class="container hero-grid"><div class="hero-copy">
    ${eyebrow(home ? t('Golf intelligence, by Data2Gain','Golf intelligence, by Data2Gain') : coach ? t('Para coaches y academias','For coaches & academies') : t('Para jugadores','For players'))}
    <h1>${title}</h1><p class="hero-description">${desc}</p>
    <div class="hero-actions">${home ? link(route('players'),t('Para jugadores','For players'),'gold','audience_players') + link(route('coaches'),t('Para coaches','For coaches'),'outline','audience_coaches') : coach ? link(mail(t('Demostración para coaches','Coach demonstration')),t('Solicitar demo por email','Request a demo by email'),'gold','coach_contact') : link(app,t('Empezar con Data2Gain','Get started with Data2Gain'),'gold','app_open')}</div>
    <p class="hero-footnote">${home ? t('Del campo al análisis. Del análisis a tu próximo golpe.', 'From the course to insight. From insight to your next shot.') : coach ? t('Cuéntanos cómo trabajas con tus jugadores.', 'Tell us how you work with your players.') : t('8,95 €/mes · Todas las funciones PRO · Cancela cuando quieras','€8.95/month · All PRO features · Cancel anytime')}</p>
    </div><div class="hero-visual ${coach ? 'hero-coaching' : ''}"><img class="hero-photo" src="/assets/editorial/${coach ? 'coaching.jpg' : 'golfer.webp'}" alt="${coach ? t('Un instructor acompaña a una joven golfista durante una sesión de práctica','An instructor guides a young golfer during practice') : t('Golfista terminando su swing con la luz del atardecer','Golfer finishing a swing in the evening light')}" width="${coach ? 1400 : 1600}" height="${coach ? 1845 : 1067}" fetchpriority="high">
    <div class="photo-caption"><span>${t('Una nueva forma de ver el golf','A new perspective on golf')}</span><span>01 — D2G</span></div>
    <a class="hero-insight" href="${coach ? '#enfoque' : '#producto'}">${coach ? `<span class="insight-icon">${diagonal}</span>` : `<img class="hero-product-peek" src="/assets/screens/${lang}/screen-dispersion-360.webp" width="78" height="86" alt="${t('Vista del análisis de dispersión','Dispersion analysis preview')}">`}<div><span class="eyebrow">${coach ? t('Al servicio de tu criterio','Built around your expertise') : t('Dentro de Data2Gain','Inside Data2Gain')}</span><strong>${coach ? t('Cada jugador tiene su historia.','Every player has a story.') : t('Tus patrones, a la vista.','Your patterns, in focus.')}</strong><span class="insight-detail">${coach ? t('Dale contexto con sus datos','Put their data into context') : t('Dispersión · Strokes Gained · IA','Dispersion · Strokes Gained · AI')}</span></div></a>
    </div></div><div class="container hero-baseline"><span>${t('SIENTE EL GOLPE. ENTIENDE EL JUEGO.','FEEL THE SHOT. UNDERSTAND THE GAME.')}</span><a href="${coach ? '#enfoque' : '#como-funciona'}">${t('Explora Data2Gain','Explore Data2Gain')}<span aria-hidden="true">↓</span></a></div></section>`;
}

function how() {
  const steps = [
    [t('Juega. Registra.','Play. Record.'),t('Añade tu ronda a Data2Gain. Todo empieza por tus propios golpes.','Add your round to Data2Gain. It all starts with your own shots.')],
    [t('Encuentra el patrón.','Find the pattern.'),t('Conoce tus distancias y descubre dónde ganas o pierdes golpes.','Know your distances and discover where you gain or lose strokes.')],
    [t('Decide el siguiente paso.','Choose your next step.'),t('Lleva una prioridad clara a tu próxima práctica o sesión con tu coach.','Take a clear priority into your next practice or coaching session.')]
  ];
  return `<section class="section section-light" id="como-funciona"><div class="container"><div class="section-heading horizontal">${eyebrow(t('01 / Del dato a la decisión','01 / From data to decisions'))}<h2>${t('Más claridad.<br>En cada paso.','More clarity.<br>At every step.')}</h2><p>${t('No necesitas saber de estadística.<br>Solo querer entender mejor tu golf.','You do not need to be a statistician.<br>Just curious about your golf.')}</p></div><div class="steps">${steps.map(([title,body],i)=>`<article class="step"><span class="step-number">0${i+1}</span><h3>${title}</h3><p>${body}</p></article>`).join('')}</div></div></section>`;
}

function audiences() {
  return `<section class="section section-light audience-section"><div class="container"><div class="section-heading"><div>${eyebrow(t('02 / Una ambición compartida','02 / One shared ambition'))}<h2>${t('Mejor golf.<br>Desde tu perspectiva.','Better golf.<br>From your perspective.')}</h2></div><p>${t('Dos formas de llegar al mismo lugar:<br>entender el juego para hacerlo crecer.','Two ways to get to the same place:<br>understand the game to help it grow.')}</p></div><div class="audience-grid">
    <a class="audience-card" href="${route('players')}" data-track="audience_players"><img src="/assets/editorial/golfer.webp" alt="${t('Golfista en el campo al atardecer','Golfer on the course at sunset')}" width="1600" height="1067" loading="lazy"><div class="audience-content"><span class="eyebrow">${t('Tu próxima mejor ronda','Your next better round')}</span><h3>${t('Soy jugador','I am a player')}</h3><p>${t('Conoce tus puntos fuertes.<br>Trabaja donde más importa.','Know your strengths.<br>Work where it matters most.')}</p><span class="text-link">${t('Descubre tu ventaja','Find your advantage')}${arrow}</span></div></a>
    <a class="audience-card" href="${route('coaches')}" data-track="audience_coaches"><img src="/assets/editorial/coaching.jpg" alt="${t('Instructor guiando a una alumna en la práctica de golf','Instructor guiding a student during golf practice')}" width="1400" height="1845" loading="lazy"><div class="audience-content"><span class="eyebrow">${t('Su progreso. Tu experiencia.','Their progress. Your expertise.')}</span><h3>${t('Soy coach','I am a coach')}</h3><p>${t('Dale contexto a cada ronda.<br>Orienta cada entrenamiento.','Give every round context.<br>Give every session direction.')}</p><span class="text-link">${t('Descubre la plataforma','Explore the platform')}${arrow}</span></div></a>
    </div></div></section>`;
}

function strategy() {
  return `<section class="section strategy-section" id="demo"><div class="container strategy-grid"><div class="strategy-copy">${eyebrow(t('03 / Explora una decisión','03 / Explore a decision'))}<h2>${t('Un mismo hoyo.<br>Dos formas<br>de <em>jugarlo.</em>','One hole.<br>Two ways<br>to <em>play it.</em>')}</h2><p>${t('Más distancia no siempre significa una mejor posición. Compara dos estrategias y observa cómo cambia el equilibrio entre avance y riesgo.','More distance does not always mean a better position. Compare two strategies and see how progress and risk change.')}</p><p class="demo-label">${t('Demostración ilustrativa · Datos de ejemplo','Illustrative demonstration · Sample data')}</p>
    <div class="strategy-controls" role="group" aria-label="${t('Estrategia del hoyo','Hole strategy')}"><button type="button" data-strategy="controlled" aria-pressed="true">${t('Control','Control')}<span>${t('Madera 3','3-wood')}</span></button><button type="button" data-strategy="aggressive" aria-pressed="false">${t('Distancia','Distance')}<span>Driver</span></button></div>
    <div class="strategy-result" aria-live="polite" aria-atomic="true"><span class="eyebrow">${t('La lectura del hoyo','Reading the hole')}</span><h3 data-strategy-title>${t('Una zona de caída más amplia.','A wider landing area.')}</h3><p data-strategy-description>${t('La madera 3 se queda antes del estrechamiento. Menos distancia, más margen para el siguiente golpe.','The 3-wood lands before the fairway narrows. Less distance, more room for your next shot.')}</p><div class="strategy-metrics"><span><strong data-strategy-distance>240 yd</strong>${t('Distancia ilustrativa','Illustrative distance')}</span><span><strong data-strategy-risk>${t('Menor','Lower')}</strong>${t('Exposición al agua','Exposure to water')}</span></div></div>
    </div><div class="course-visual" data-course-strategy="controlled"><div class="course-top"><span>${t('HOYO DE EJEMPLO','SAMPLE HOLE')}</span><span>PAR 4 / 418 YD</span></div><img src="/assets/hero-hole-sg-1200.webp" srcset="/assets/hero-hole-sg-480.webp 480w, /assets/hero-hole-sg-800.webp 800w, /assets/hero-hole-sg-1200.webp 1200w" sizes="(max-width: 760px) 92vw, 52vw" width="1264" height="848" loading="lazy" alt="${t('Ilustración de un hoyo con un obstáculo de agua junto a la calle','Illustration of a golf hole with water beside the fairway')}"><svg class="course-path" viewBox="0 0 1264 848" aria-hidden="true"><path class="route-controlled" d="M610 800 Q610 620 602 535"/><path class="route-aggressive" d="M610 800 Q590 550 550 348"/><ellipse class="landing-controlled" cx="602" cy="535" rx="35" ry="54"/><ellipse class="landing-aggressive" cx="550" cy="348" rx="49" ry="71"/></svg><div class="course-marker"><span class="marker-dot"></span><strong data-strategy-marker>${t('Más margen de calle','More fairway to work with')}</strong></div><div class="course-bottom"><span class="legend-dot"></span><span>${t('Trayectoria y zona de caída orientativas','Illustrative shot path and landing area')}</span></div></div></div></section>`;
}

function screenshot(name, alt, extra = '') {
  return `<button class="screenshot-button ${extra}" type="button" data-zoom="/assets/screens/${lang}/${name}.png" aria-label="${esc(t('Ampliar: ','Enlarge: ')+alt)}"><img src="/assets/screens/${lang}/${name}-800.webp" srcset="/assets/screens/${lang}/${name}-360.webp 360w, /assets/screens/${lang}/${name}-800.webp 800w" sizes="(max-width: 760px) 88vw, 44vw" alt="${esc(alt)}" width="800" height="900" loading="lazy"><span class="zoom-indicator">${diagonal}<span>${t('Ampliar','Enlarge')}</span></span></button>`;
}

function product() {
  const tabs = [t('Dispersión','Dispersion'),t('Distancias','Distances'),t('Putting','Putting')];
  const titles = [t('Tu patrón real.<br>A simple vista.','Your real pattern.<br>At a glance.'),t('Cada palo.<br>Su distancia.','Every club.<br>Its distance.'),t('El green también<br>cuenta una historia.','The green tells<br>a story, too.')];
  const descriptions = [t('Los buenos golpes son una parte de la historia. Mira también dónde terminan los demás y encuentra una referencia más útil para apuntar.','Great shots are only part of the story. See where the others finish and find a more useful reference for aiming.'),t('Consulta tus distancias habituales e identifica los huecos entre palos. Llega a la siguiente decisión con una referencia basada en tu juego.','See your usual distances and identify gaps between clubs. Make your next decision with a reference based on your game.'),t('Observa cómo cambia tu efectividad según la distancia. Pon el foco de la práctica donde tus datos muestran más margen.','See how your putting changes with distance. Focus your practice where your data shows room for improvement.')];
  const images = ['screen-dispersion','screen-gap','screen-putt'];
  return `<section class="section section-light product-section" id="producto"><div class="container"><div class="section-heading"><div>${eyebrow(t('04 / Dentro de Data2Gain','04 / Inside Data2Gain'))}<h2>${t('La diferencia está<br>en lo que descubres.','The difference is<br>what you discover.')}</h2></div><p>${t('Pantallas del producto.<br>Conclusiones que puedes llevar al campo.','Screens from the product.<br>Insights you can take to the course.')}</p></div><div class="product-tabs" role="tablist" aria-label="${t('Explorar funciones','Explore features')}">${tabs.map((text,i)=>`<button id="product-tab-${i}" type="button" role="tab" aria-selected="${i === 0}" aria-controls="product-panel-${i}" tabindex="${i === 0 ? '0' : '-1'}" data-product-tab="${i}"><span>0${i+1}</span>${text}</button>`).join('')}</div>${tabs.map((_,i)=>`<div class="product-panel" id="product-panel-${i}" role="tabpanel" aria-labelledby="product-tab-${i}" tabindex="0"${i ? ' hidden' : ''}><div class="product-screen">${screenshot(images[i],tabs[i])}<p class="screen-caption">${t('Captura de Data2Gain · Ejemplo de análisis','Data2Gain screenshot · Example analysis')}</p></div><div class="product-copy"><h3>${titles[i]}</h3><p>${descriptions[i]}</p><a class="text-link" href="${app}" data-track="app_open">${t('Explorar la app','Explore the app')}${arrow}</a><div class="product-detail"><span class="detail-rule"></span><p>${t('Tus rondas ponen los datos.<br>Tú decides el siguiente paso.','Your rounds provide the data.<br>You choose the next step.')}</p></div></div></div>`).join('')}</div></section>`;
}

function benchmark() {
  const values = compareRound('5').values;
  const labels = [t('Salidas','Off the tee'),t('Aproximación','Approach'),t('Juego corto','Short game'),'Putting'];
  return `<section class="section benchmark-section" id="strokes-gained"><div class="container benchmark-grid"><div>${eyebrow(t('Tu juego, en contexto','Your game, in context'))}<h2>${t('Elige tu referencia.<br>Entiende tu<br><em>rendimiento.</em>','Choose a benchmark.<br>Understand your<br><em>performance.</em>')}</h2><p>${t('Strokes Gained compara los golpes ganados o perdidos frente a un nivel de referencia. Aquí ves la misma ronda de ejemplo comparada con distintos niveles.','Strokes Gained compares strokes gained or lost against a benchmark. Here, the same sample round is compared with different levels.')}</p><p class="demo-label">${t('Datos ilustrativos. No es un diagnóstico personal.','Illustrative data. This is not a personal assessment.')}</p><label class="select-label" for="benchmark-select">${t('Nivel de referencia','Reference level')}</label><select id="benchmark-select">${[['tour','Tour'],['0','HCP 0'],['5','HCP 5'],['10','HCP 10'],['15','HCP 15'],['20','HCP 20']].map(([key,label])=>`<option value="${key}"${key === '5' ? ' selected' : ''}>${label}</option>`).join('')}</select></div><div class="benchmark-chart"><div class="chart-heading"><span>${t('MISMA RONDA / OTRA PERSPECTIVA','SAME ROUND / ANOTHER PERSPECTIVE')}</span><span data-benchmark-label>VS HCP 5</span></div><div class="benchmark-rows">${labels.map((label,i)=>`<div class="benchmark-row"><span>${label}</span><div class="diverging-track"><span class="zero-line"></span><span data-sg-bar="${i}" class="sg-bar ${values[i]<0?'negative':'positive'}" style="--bar-size:${Math.min(Math.abs(values[i])/2*50,50)}%"></span></div><strong data-sg-value="${i}">${values[i]>0?'+':''}${values[i].toFixed(2)}</strong></div>`).join('')}</div><div class="chart-axis"><span>− SG</span><span>0</span><span>+ SG</span></div><p class="benchmark-insight" data-benchmark-insight aria-live="polite">${t('Frente a HCP 5, el putting es el área con más margen en esta ronda de ejemplo.','Against HCP 5, putting offers the most room for improvement in this sample round.')}</p><div class="round-facts"><span><strong>${round.distance} yd</strong>${t('Distancia de salida','Driving distance')}</span><span><strong>${round.fairways}%</strong>${t('Calles alcanzadas','Fairways hit')}</span><span>${t('Los datos de la ronda<br>se mantienen iguales.','The round data<br>stays the same.')}</span></div></div></div></section>`;
}

function aiTeaser() {
  return `<section class="section section-light ai-teaser"><div class="container"><div>${eyebrow(t('El agente IA de Data2Gain','The Data2Gain AI agent'))}<h2>${t('Tus preguntas.<br>El contexto de tus rondas.','Your questions.<br>The context of your rounds.')}</h2></div><div><p>${t('Pregunta qué trabajar y explora tus patrones. El agente te ayuda a interpretar el análisis para dar el siguiente paso.','Ask what to work on and explore your patterns. The agent helps you interpret your analysis and find your next step.')}</p><a class="text-link" href="${route('players')}#agente">${t('Conoce el agente IA','Meet the AI agent')}${arrow}</a></div></div></section>`;
}
function ai() {
  return `<section class="section section-light ai-section" id="agente"><div class="container ai-grid"><div>${eyebrow(t('Una conversación con tu juego','A conversation with your game'))}<h2>${t('Pregunta mejor.<br><em>Entrena con foco.</em>','Ask better questions.<br><em>Practice with focus.</em>')}</h2><p>${t('Conecta tus preguntas con el análisis de tus rondas. El agente de Data2Gain te ayuda a interpretar los datos y a identificar prioridades.','Connect your questions with your round analysis. The Data2Gain agent helps you interpret the data and identify priorities.')}</p><a class="text-link" href="${app}" data-track="app_open">${t('Conocer el agente IA','Explore the AI agent')}${arrow}</a></div><div class="ai-example"><span class="eyebrow">${t('Ejemplo de conversación','Example conversation')}</span><div class="chat-question">${t('¿Qué debería trabajar en mi próxima sesión?','What should I work on in my next practice session?')}</div><div class="chat-answer"><span class="agent-signature">${brand()} <span>AGENT</span></span><p>${t('En esta ronda de ejemplo, el putting es el área con más margen frente a HCP 5. Empieza por revisar tu efectividad en putts de media distancia.','In this sample round, putting has the most room for improvement against HCP 5. Start by reviewing your make rate on mid-range putts.')}</p><div class="chat-focus"><span>${t('PRIORIDAD A EXPLORAR','PRIORITY TO EXPLORE')}</span><strong>Putting <span>−0.24 SG</span></strong></div></div><p class="sample-note">${t('Respuesta ilustrativa. El análisis real depende de tus rondas.','Illustrative response. Your actual analysis depends on your rounds.')}</p></div></div></section>`;
}

function pricing() {
  return `<section class="section section-light pricing-section" id="precios"><div class="container"><div class="section-heading"><div>${eyebrow(t('Tu siguiente paso','Your next step'))}<h2>${t('Empieza por<br>entender tu juego.','Start by<br>understanding your game.')}</h2></div><p>${t('Elige el camino que encaja contigo.','Choose the path that fits you.')}</p></div><div class="pricing-grid"><article class="price-card"><div class="price-card-top"><span class="eyebrow">${t('Para jugadores','For players')}</span><span class="plan-badge">DATA2GAIN PRO</span></div><p class="price">${t('8,95 €','€8.95')}<span>${t('/ mes','/ month')}</span></p><p>${t('Todas las funciones PRO en un solo plan.','All PRO features in one plan.')}</p><ul class="check-list">${[t('Análisis Strokes Gained','Strokes Gained analysis'),t('Dispersión y distancias por palo','Club dispersion and distances'),t('Agente IA y análisis de tus rondas','AI agent and round analysis')].map(text=>`<li>${check}${text}</li>`).join('')}</ul>${link(app,t('Empezar con Data2Gain','Get started with Data2Gain'),'dark','app_open')}<p class="price-note">${t('Suscripción mensual. Cancela cuando quieras.','Monthly subscription. Cancel anytime.')}</p></article><article class="price-card price-coaches"><span class="eyebrow">${t('Para coaches y academias','For coaches & academies')}</span><h3>${t('Tu forma de enseñar.<br>Con más contexto.','Your way of coaching.<br>With more context.')}</h3><p>${t('Conoce cómo incorporar Data2Gain a tu trabajo con jugadores y qué opción encaja con tu actividad.','Discover how to bring Data2Gain into your work with players and find the right option for your practice.')}</p><ul class="check-list">${[t('Plataforma para coaches','Platform for coaches'),t('Consultoría sobre análisis del juego','Game analysis consulting'),t('Formación para integrar los datos','Training to put data to work')].map(text=>`<li>${check}${text}</li>`).join('')}</ul>${link(mail(t('Información y demostración para coaches','Coach information and demonstration')),t('Solicitar demo por email','Request a demo by email'),'outline-dark','coach_contact')}<p class="price-note">${t('Condiciones profesionales a consultar.','Contact us for professional terms.')}</p></article></div></div></section>`;
}

function faq() {
  const items = [
    [t('¿Necesito saber de estadística?','Do I need to understand statistics?'),t('No. Strokes Gained pone tu rendimiento en contexto: un valor positivo indica golpes ganados frente a la referencia y uno negativo, golpes perdidos. Los gráficos y el agente IA te ayudan a interpretar el análisis.','No. Strokes Gained puts your performance into context: a positive value means strokes gained against your benchmark; a negative value means strokes lost. Charts and the AI agent help you interpret the analysis.')],
    [t('¿Cómo empiezo a usar Data2Gain?','How do I start using Data2Gain?'),t('Accede a la app web, sigue el proceso de acceso y añade tus rondas con las opciones disponibles en la plataforma. Podrás consultar las condiciones de contratación antes de suscribirte.','Open the web app, follow the sign-in process and add your rounds using the options available in the platform. You can review subscription terms before subscribing.')],
    [t('¿Dónde puedo utilizar la app?','Where can I use the app?'),t('Puedes acceder a Data2Gain desde el navegador de tu móvil, tablet u ordenador en app.data2gain.com.','You can access Data2Gain from your phone, tablet or computer browser at app.data2gain.com.')],
    [t('¿Los ejemplos muestran mis resultados?','Do the examples show my results?'),t('No. La demostración del hoyo, el comparador y la conversación usan datos ilustrativos. Las capturas muestran ejemplos del producto. Tu análisis se basa en las rondas que añadas a la app.','No. The hole demonstration, benchmark comparison and conversation use illustrative data. Screenshots show examples of the product. Your analysis is based on the rounds you add to the app.')],
    [t('¿La suscripción de jugador incluye una cuenta de coach?','Does the player subscription include a coach account?'),t('El precio de 8,95 €/mes corresponde al plan Data2Gain PRO para jugadores. Para conocer las condiciones de coaches, academias, consultoría o formación, contacta con info@data2gain.com.','The €8.95/month price refers to the Data2Gain PRO player plan. Contact info@data2gain.com for coach, academy, consulting or training terms.')]
  ];
  return `<section class="section section-light faq-section"><div class="container faq-grid"><div>${eyebrow(t('Antes de empezar','Before you begin'))}<h2>${t('Las cosas,<br>claras.','Let’s make<br>things clear.')}</h2><p>${t('Si te queda alguna duda, hablamos.','If you have another question, get in touch.')}</p><a class="text-link" href="mailto:info@data2gain.com">info@data2gain.com${diagonal}</a></div><div class="faq-list">${items.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>`;
}

function closing(page) {
  const coach = page === 'coaches';
  return `<section class="closing"><div class="container closing-inner">${eyebrow(t('El próximo golpe empieza aquí','Your next shot starts here'))}<h2>${t('Juega con intuición.<br><em>Decide con perspectiva.</em>','Play with intuition.<br><em>Decide with perspective.</em>')}</h2><div class="hero-actions">${coach ? link(mail(t('Demostración para coaches','Coach demonstration')),t('Hablemos de tus jugadores','Let’s talk about your players'),'gold','coach_contact') : link(route('players'),t('Soy jugador','I am a player'),'gold','audience_players') + link(route('coaches'),t('Soy coach','I am a coach'),'outline','audience_coaches')}</div></div></section>`;
}

function coachContent() {
  const blocks = [
    [t('Antes de la sesión','Before the session'),t('Llega con una perspectiva más completa.','Start with a clearer picture.'),t('Las rondas ponen contexto a lo que ves en la práctica. Explora los patrones de juego y detecta los temas que merece la pena trabajar juntos.','Rounds give context to what you see in practice. Explore patterns and identify the topics worth working on together.')],
    [t('Durante la sesión','During the session'),t('Haz visible tu explicación.','Make your explanation visible.'),t('Apóyate en distancias, dispersión y Strokes Gained para explicar una prioridad. Los datos acompañan tu criterio profesional.','Use distances, dispersion and Strokes Gained to explain a priority. Data supports your professional judgement.')],
    [t('Después de la sesión','After the session'),t('Vuelve a los datos. Revisa el progreso.','Return to the data. Review progress.'),t('Usa las nuevas rondas como punto de partida para la siguiente conversación y ajusta el foco del entrenamiento.','Use new rounds as a starting point for your next conversation and adjust the focus of practice.')]
  ];
  return `<section class="section section-light" id="enfoque"><div class="container"><div class="section-heading"><div>${eyebrow(t('Datos al servicio del coaching','Data in service of coaching'))}<h2>${t('La conversación cambia<br>cuando ves el juego.','The conversation changes<br>when you can see the game.')}</h2></div></div><div class="coach-steps">${blocks.map(([k,h,p],i)=>`<article><span class="step-number">0${i+1}</span>${eyebrow(k)}<h3>${h}</h3><p>${p}</p></article>`).join('')}</div></div></section>
  <section class="section coach-product"><div class="container ai-grid"><div>${eyebrow(t('Una referencia compartida','A shared reference'))}<h2>${t('Sus patrones.<br>Tu interpretación.','Their patterns.<br>Your interpretation.')}</h2><p>${t('El análisis de dispersión ayuda a poner una imagen a las tendencias de cada palo. Una herramienta para conversar, priorizar y trabajar con el jugador.','Dispersion analysis helps put a picture to each club’s tendencies. A tool for conversation, priorities and working with your player.')}</p><p class="demo-label">${t('Captura de análisis de jugador. Consulta la experiencia para coaches en una demostración.','Player analysis screenshot. Request a demonstration of the coach experience.')}</p>${link(mail(t('Ver experiencia para coaches','See the coach experience')),t('Solicitar demo por email','Request a demo by email'),'gold','coach_contact')}</div><div class="coach-screen">${screenshot('screen-dispersion',t('Análisis de dispersión del jugador','Player dispersion analysis'))}</div></div></section>
  <section class="section section-light"><div class="container"><div class="section-heading"><div>${eyebrow(t('También te acompañamos','More ways to work together'))}<h2>${t('Del análisis<br>a tu método.','From analysis<br>to your method.')}</h2></div></div><div class="services-list">${[[t('Consultoría','Consulting'),t('Te ayudamos a interpretar los datos y a incorporarlos a la planificación del trabajo con tus jugadores.','Get help interpreting data and bringing it into your work with players.')],[t('Formación','Training'),t('Sesiones para coaches que quieren integrar Strokes Gained y análisis de datos en su enseñanza.','Sessions for coaches who want to bring Strokes Gained and data analysis into their teaching.')]].map(([h,p],i)=>`<article><span class="service-number">0${i+1}</span><div><h3>${h}</h3><p>${p}</p></div><a class="text-link" href="${mail(h)}" data-track="coach_contact">${t('Consultar por email','Enquire by email')}${diagonal}</a></article>`).join('')}</div></div></section>`;
}

function info() {
  return `<section class="section section-light info-page"><div class="container narrow">${eyebrow('Data2Gain')}<h1>${t('Información<br>y contacto.','Information<br>& contact.')}</h1><p class="lead">${t('Un punto de contacto para tus preguntas sobre Data2Gain.','A point of contact for your questions about Data2Gain.')}</p><article><h2>${t('Contacta con nosotros','Get in touch')}</h2><p>${t('Para información sobre la app, coaches, formación, condiciones de servicio o privacidad, escribe a','For information about the app, coaches, training, service terms or privacy, email')} <a href="mailto:info@data2gain.com">info@data2gain.com</a>.</p></article><article><h2>${t('Esta web y la aplicación','This website and the application')}</h2><p>${t('Esta web presenta Data2Gain y ejemplos de sus análisis. El acceso a la plataforma y la contratación se realizan en la aplicación. Revisa allí las condiciones aplicables antes de contratar.','This website presents Data2Gain and examples of its analysis. Platform access and subscriptions take place in the application. Review the applicable terms there before subscribing.')}</p>${link(app,t('Ir a la aplicación','Open the application'),'dark','app_open')}</article><article><h2>${t('Navegación y privacidad','Browsing and privacy')}</h2><p>${t('Los controles de demostración funcionan en tu navegador y no envían los valores seleccionados a un servidor. Esta versión de la web no incorpora formularios, cookies analíticas ni rastreadores publicitarios. Al contactar por email o acceder a la aplicación se abre un servicio distinto.','Demo controls run in your browser and do not send selected values to a server. This version of the website has no forms, analytics cookies or advertising trackers. Email contact and application links open a separate service.')}</p><p>${t('Para consultar la información legal completa o ejercer una solicitud sobre tus datos, contacta con info@data2gain.com.','For full legal information or requests concerning your data, contact info@data2gain.com.')}</p></article><article><h2>${t('Sobre las demostraciones','About the demonstrations')}</h2><p>${t('El mapa, el comparador de Strokes Gained y la conversación de IA contienen datos ilustrativos. No son un diagnóstico personal ni una garantía de mejora. Las fotografías ilustran la práctica del golf y no representan testimonios ni avales de sus protagonistas.','The map, Strokes Gained comparison and AI conversation contain illustrative data. They are not a personal assessment or a guarantee of improvement. Photos illustrate golf and do not represent testimonials or endorsements by the people pictured.')}</p></article><article><h2>${t('Créditos de fotografía','Photography credits')}</h2><p><a href="https://unsplash.com/photos/bJkezZ4W_So">Braden Egli / Unsplash</a> · <a href="https://www.pexels.com/photo/1325652/">Jopwell / Pexels</a>.</p></article></div></section>`;
}

function document(page) {
  const titles = { home:t('Data2Gain | Tu juego. Tus datos. Tu ventaja.','Data2Gain | Your game. Your data. Your advantage.'), players:t('Data2Gain para jugadores | Entiende tu golf','Data2Gain for players | Understand your golf'), coaches:t('Data2Gain para coaches y academias','Data2Gain for coaches & academies'), info:t('Información y contacto | Data2Gain','Information & contact | Data2Gain') };
  const description = page === 'coaches' ? t('Analítica de golf al servicio de tu coaching. Descubre Data2Gain para coaches y academias, consultoría y formación.','Golf analytics in service of your coaching. Explore Data2Gain for coaches and academies, consulting and training.') : t('Convierte tus rondas en mejores decisiones. Strokes Gained, distancias, dispersión y análisis con IA para jugadores y coaches.','Turn your rounds into better decisions. Strokes Gained, distances, dispersion and AI analysis for players and coaches.');
  const content = page === 'home' ? hero(page)+how()+audiences()+strategy()+product()+aiTeaser()+pricing()+faq()+closing(page) : page === 'players' ? hero(page)+how()+benchmark()+product()+ai()+pricing()+faq()+closing(page) : page === 'coaches' ? hero(page)+coachContent()+closing(page) : info();
  const schema = { '@context':'https://schema.org', '@type': page === 'info' ? 'ContactPage' : 'WebPage', name:titles[page], description, url:origin+route(page), inLanguage:lang, isPartOf:{'@type':'WebSite',name:'Data2Gain',url:origin} };
  return `<!doctype html>\n<html lang="${lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${titles[page]}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#101412"><link rel="canonical" href="${origin+route(page)}"><link rel="alternate" hreflang="es" href="${origin+route(page,'es')}"><link rel="alternate" hreflang="en" href="${origin+route(page,'en')}"><link rel="alternate" hreflang="x-default" href="${origin+route(page,'es')}"><link rel="icon" href="/favicon.ico" sizes="any"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="manifest" href="/site-${lang}.webmanifest"><meta property="og:type" content="website"><meta property="og:title" content="${titles[page]}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin+route(page)}"><meta property="og:image" content="https://data2gain.com/assets/hero-hole-sg.jpg"><meta property="og:locale" content="${lang==='es'?'es_ES':'en_US'}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${titles[page]}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="https://data2gain.com/assets/hero-hole-sg.jpg"><link rel="stylesheet" href="/css/premium.css?v=3"><script type="application/ld+json">${JSON.stringify(schema)}</script><script type="module" src="/js/premium.js?v=3"></script></head><body class="page-${page}">${header(page)}<main id="main">${content}</main>${footer()}</body></html>\n`;
}

await mkdir(path.join(root,'dist'),{recursive:true});
const publicPages = [];
for (const locale of ['es','en']) {
  lang=locale;
  for (const page of Object.keys(slugs[locale])) {
    const relative=`${locale}/${slugs[locale][page]}index.html`;
    const html=document(page);
    for (const base of [root,path.join(root,'dist')]) {
      await mkdir(path.dirname(path.join(base,relative)),{recursive:true});
      await writeFile(path.join(base,relative),html);
    }
    publicPages.push(route(page));
    if(locale==='es' && page==='home') for(const base of [root,path.join(root,'dist')]) await writeFile(path.join(base,'index.html'),html);
  }
}
const sitemap=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${publicPages.map(p=>`<url><loc>${origin+p}</loc></url>`).join('')}</urlset>\n`;
const robots=`User-agent: *\nAllow: /\nDisallow: /backups/\nDisallow: /scripts/\nDisallow: /tests/\nSitemap: ${origin}/sitemap.xml\n`;
for (const base of [root,path.join(root,'dist')]) {
  await writeFile(path.join(base,'sitemap.xml'),sitemap);
  await writeFile(path.join(base,'robots.txt'),robots);
}
for (const dir of ['assets','css','js']) await cp(path.join(root,dir),path.join(root,'dist',dir),{recursive:true});
for (const filename of (await readdir(root)).filter(n=>/^(favicon.*|apple-touch-icon\.png|icon-.*\.png|site-.*\.webmanifest|\.htaccess)$/.test(n))) await cp(path.join(root,filename),path.join(root,'dist',filename));
console.log(`Built ${publicPages.length} localized pages + Spanish root. Public output: dist/`);
